[package]
name = "dagger-pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
dagger-sdk = "0.8.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

