name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'crates/stack-cli.com/**'
      - '.devcontainer/**'
      - '*.md'
      - '.github/workflows/release*.yml'
      - '.github/workflows/spell-check.yml'
      - Justfile
      - README.md
  pull_request:
    paths-ignore:
      - 'crates/stack-cli.com/**'
      - '.devcontainer/**'
      - '*.md'
      - '.github/workflows/release*.yml'
      - '.github/workflows/spell-check.yml'
      - Justfile
      - README.md

jobs:
  build:
    name: Run Dagger build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dagger build
        id: dagger
        continue-on-error: true
        run: cargo run -p dagger-pipeline -- build linux
        env:
          DAGGER_LOG_FORMAT: plain

      - name: Build and publish demo app image
        if: github.ref_name == 'main'
        run: cargo run -p dagger-pipeline -- demo-app
        env:
          DAGGER_LOG_FORMAT: plain
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STACK_DEMO_APP_TAGS: latest
